version: "3"

services:
  nginx:
    image: nginx
    restart: always
    links:
      # - client
      - server
    depends_on:
      # - client
      - server
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  # client:
  #   build: ./client
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - API_URL=http://localhost:8081/api

  api:
    build: ./api
    ports:
      - 8081:8081
    volumes:
      - ./api:/app
    depends_on:
      - database
    environment:
      - DATABASE_URL=database

  database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./database:/app/database
